### PR TITLE
Legendre shortcut: truncate loop over m

### LINKED ISSUE #131: Shortening the Legendre Transform over m
This is an issue to collect ideas around the linear vs quadratic vs cubic truncation when looping over the zonal wavenumbers $m$. With #127 we'll do 
```julia
for m in 1:min(nfreq:mmax+1)
```
with `nfreq  = nlon÷2 + 1` and `nlon` the number of longitude points at a given latitude ring. So for full grids, the loop goes over all `m` but for reduced grids this can be shortened. IFS seems to be doing the following (`j` `nlon` `nfreq`) at Tco79
```
 (   1  20   8) (   2  24  10) (   3  28  12) (   4  32  14) (   5  36  16) (   6  40  18) (   7  44  20) (   8  48  22)
 (   9  52  24) (  10  56  26) (  11  60  27) (  12  64  29) (  13  68  31) (  14  72  33) (  15  76  35) (  16  80  36)
 (  17  84  38) (  18  88  40) (  19  92  41) (  20  96  43) (  21 100  44) (  22 104  46) (  23 108  47) (  24 112  49)
 (  25 116  50) (  26 120  52) (  27 124  53) (  28 128  55) (  29 132  56) (  30 136  57) (  31 140  58) (  32 144  60)
 (  33 148  61) (  34 152  62) (  35 156  63) (  36 160  64) (  37 164  65) (  38 168  67) (  39 172  68) (  40 176  69)
 (  41 180  70) (  42 184  71) (  43 188  72) (  44 192  73) (  45 196  74) (  46 200  75) (  47 204  76) (  48 208  77)
 (  49 212  78) (  50 216  79) (  51 220  79) (  52 224  79) (  53 228  79) (  54 232  79) (  55 236  79) (  56 240  79)
 (  57 244  79) (  58 248  79) (  59 252  79) (  60 256  79) (  61 260  79) (  62 264  79) (  63 268  79) (  64 272  79)
 (  65 276  79) (  66 280  79) (  67 284  79) (  68 288  79) (  69 292  79) (  70 296  79) (  71 300  79) (  72 304  79)
 (  73 308  79) (  74 312  79) (  75 316  79) (  76 320  79) (  77 324  79) (  78 328  79) (  79 332  79) (  80 336  79)
 (  81 336  79) (  82 332  79) (  83 328  79) (  84 324  79) (  85 320  79) (  86 316  79) (  87 312  79) (  88 308  79)
 (  89 304  79) (  90 300  79) (  91 296  79) (  92 292  79) (  93 288  79) (  94 284  79) (  95 280  79) (  96 276  79)
 (  97 272  79) (  98 268  79) (  99 264  79) ( 100 260  79) ( 101 256  79) ( 102 252  79) ( 103 248  79) ( 104 244  79)
 ( 105 240  79) ( 106 236  79) ( 107 232  79) ( 108 228  79) ( 109 224  79) ( 110 220  79) ( 111 216  79) ( 112 212  78)
 ( 113 208  77) ( 114 204  76) ( 115 200  75) ( 116 196  74) ( 117 192  73) ( 118 188  72) ( 119 184  71) ( 120 180  70)
 ( 121 176  69) ( 122 172  68) ( 123 168  67) ( 124 164  65) ( 125 160  64) ( 126 156  63) ( 127 152  62) ( 128 148  61)
 ( 129 144  60) ( 130 140  58) ( 131 136  57) ( 132 132  56) ( 133 128  55) ( 134 124  53) ( 135 120  52) ( 136 116  50)
 ( 137 112  49) ( 138 108  47) ( 139 104  46) ( 140 100  44) ( 141  96  43) ( 142  92  41) ( 143  88  40) ( 144  84  38)
 ( 145  80  36) ( 146  76  35) ( 147  72  33) ( 148  68  31) ( 149  64  29) ( 150  60  27) ( 151  56  26) ( 152  52  24)
 ( 153  48  22) ( 154  44  20) ( 155  40  18) ( 156  36  16) ( 157  32  14) ( 158  28  12) ( 159  24  10) ( 160  20   8)
```
So that's about 3 fewer m around the poles and less than half at the Equator
```julia
julia> cat(ifs[1:80],spd,spd-ifs[1:80],dims=2)
80×3 Matrix{Int64}:
  8  10  2
 10  12  2
 12  14  2
 14  16  2
 16  18  2
 18  20  2
 20  22  2
 22  24  2
 24  26  2
 26  28  2
 27  30  3
 29  32  3
 31  34  3
 33  36  3
 35  38  3
 36  40  4
 38  42  4
 40  44  4
 41  46  5
 43  48  5
 44  50  6
 46  52  6
 47  54  7
 49  56  7
 50  58  8
 52  60  8
 ⋮
```
and apparently follows the formula `nfreq = floor((nlon - 1)/(2 + coslat^2))) - 1`. At that resolution this is per hemisphere 4784 loops over m compared to 6400 total (80 rings each 80 orders). Meaning there's a good amount of performance gain possible if we follow something similar. What needs to be checked though is how much this applies to other grids and whether we can directly formulate this as a function of the truncation order.

More information on this apparently in [Courtier and Naughton 1994](https://rmets.onlinelibrary.wiley.com/doi/10.1002/qj.49712051913)

@hottad @samhatfield

### PR DESCRIPTION
**Pull request by milankl**
fixes #131 

@hottad, this pull request now implements the various shortcuts over order $m$ in the Legendre Transform as discussed. I don't plan to change the default that is currently `run_speedy(legendre_shortcut=:linear)`, but as they are now implemented we can test them. The `m_truncs` (the maximum m per latitude ring) are now a field in `SpectralTransform`, which can be obtained like this
```julia
julia> P = Parameters(NF=Float64,Grid=OctahedralClenshawGrid);

julia> SpectralTransform(P).m_truncs
32-element Vector{Int64}:
 11
 13
 15
 17
 19
 21
 23
 25
 27
 29
 31
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
 32
```
and similar for `legendre_short` set to `:linear`,`:quadratic`,`:cubic`,`:linquad_coslat²`, `:lincub_coslat`, which are the options we discussed basically. (Did I miss the `m_to_retain` option or how different was that from `:linquad_coslat²`?)

### CODE REVIEW

**Comment by milankl** [comment]
More quick tests with HEALPix4Grid

image

An eddy over Japan clearly kicks off some ripples with `:cubic`, which looks better to me with `:linear` or `:quadratic` or `:linquad_coslat²` but not as good with `:lincub_coslat`. So I'll keep `:linear` as default for now, but `:quadratic` or some transition between linear and quadratic also might be reasonable. The performance gain is <10% following some quick tests, so might not be worth the effort in our case. But interesting still. @samhatfield

**Comment by hottad** [comment]
Thank you @milankl, fantastic job, as always!

I really like this flexible design. I suppose, even after initializing a `SpectralTransfom` struct with, say,
```julia
P = Parameters(NF=Float64,Grid=HEALPix4Grid,legendre_short=linear);
S=SpectralTransform(P)
```
we can overwrite `m_truncs` by `S.m_truncs=(some array)` before calling transforms, right?

I could try implementing an `m_to_retain` option, but with this very high flexibility, overwriting `S.m_trunc` with my `m_to_retain`  is good enough for experimenting.

**Comment by milankl** [comment]
Yes, if you want to experiment, you have to do something like
```julia
julia> P,D,M = initialize_speedy(some_arguments...)
julia> M.spectral_transform.m_truncs .= 24  # change the entries of m_truncs
julia> SpeedyWeather.time_stepping!(P,D,M)
```

**Comment by milankl** [comment]
Given that `m_truncs` is probably always just a function of the number of longitude points `nlon` and the latitude `lat`, we could have something convenient like
```julia
julia> f(nlon,lat) = nlon÷2 + 1
julia> run_speedy(Grid=HEALPix4Grid,legendre_shortcut=f)
```
such that one can define a function with two arguments `nlon`,`lat` and pass that on which is evaluated to get `m_truncs`. I'll do that next week!

**Comment by hottad** [comment]
Great idea! Feels like writing a lisp code.
However.... To define `m_to_retain` that I discussed in #131, I would need to do something like
```julia
function m_to_retain(ϵ_threshold::Real,S::SpectralTransform)
  m_truncs=zeros(Int, S.nlat_half)
  Pnm_j=S.Λs
  for j in 1:S.nlat_half
      for m in S.mmax:-1:0
          if abs(Pnm_j[j][S.lmax,m]) > ϵ_threshold
              m_truncs[j]=m
              break
          end
      end
  end
  m_truncs
end

P,D,M = initialize_speedy(some_arguments...)
S=M.spectral_transform
S.m_truncs=m_to_retain(1e-6,S)
SpeedyWeather.time_stepping!(P,D,M)
```
Will I still be able to do this if you refactor your code like that?

**Comment by hottad** [comment]
Ah, changing how `legendre_shortcut` is specified has nothing to do with overwriting `m_truncs`.  Sorry that I messed up...

**Comment by milankl** [comment]
I've decided against the ability to pass on a function directly as proposed here

> julia> f(nlon,lat) = nlon÷2 + 1
julia> run_speedy(Grid=HEALPix4Grid,legendre_shortcut=f)

as it seems to open a can of worms of how to do this, what arguments such a function should have (nlon, lat) might not be enough, etc. The possibility to overwrite `m_truncs` is unaffected. Will merge this now.

**Comment by hottad** [comment]
Thank you Milan! Great work!

**Pull request merged**
