### PR TITLE
Keep GPU branch up to date

### PR DESCRIPTION
**Pull request by maximilian-gelbrecht**
Merges all recent changes from `main` into `gpu`.

### CODE REVIEW

**Comment by maximilian-gelbrecht** [comment]
So, now we got the tests from `test/kernelabstractions.jl` working and it seems we directly found an error from one of the `adapt_structures` 

@katharinamaetschke can you look at that? The CI report shows an error for `SurfaceVariables`

**Comment by milankl** [comment]
The error seems to come from calling `SurfaceVariables` with `Vector`s instead of `Grid`s
```julia
 KernelAbstractions tests: Error During Test at /home/runner/work/SpeedyWeather.jl/SpeedyWeather.jl/test/kernelabstractions.jl:3
  Got exception outside of a @test
  MethodError: no method matching SpeedyWeather.SurfaceVariables(::Vector{Float64}, ::LowerTriangularMatrix{ComplexF64}, ::Vector{Float64}, ::Vector{Float64}, ::Int64)
  Closest candidates are:
    SpeedyWeather.SurfaceVariables(::Grid, ::LowerTriangularMatrix{Complex{NF}}, ::Grid, ::Grid, ::Int64) where {NF<:AbstractFloat, Grid<:AbstractGrid{NF}} at ~/work/SpeedyWeather.jl/SpeedyWeather.jl/src/diagnostic_variables.jl:255
```

**Comment by maximilian-gelbrecht** [comment]
This PR is really only meant to keep the branch updated, so I'll merge it now as there no merge conflicts. The error in the test, needs to be fixed in another PR.

**Comment by maximilian-gelbrecht** [comment]
@katharinamaetschke If you have any questions about the changes with the `Grid` type, don't hesitate to ask @milankl or me.

**Pull request merged**
